// Landing page content for each industry. `npm run build` in niches/ renders
// site/<slug>/index.html from template.mjs. Keep claims modest and true: the AI
// tools are "coming soon" until the app ships for that industry.

export const NICHES = [
  {
    slug: "quotecloser",
    brand: "QuoteCloser",
    industry: "Trades",
    audience: "HVAC, plumbing, electrical, roofing, painting & landscaping contractors",
    title: "QuoteCloser | Win more of the jobs you've already quoted",
    description: "AI follow-up for contractors: Good/Better/Best quotes, automatic quote follow-ups and more 5-star reviews. Free unsold-quote calculator.",
    eyebrow: "For contractors & home-service pros",
    headline: "Stop losing jobs you've ",
    highlight: "already quoted.",
    sub: "Most homeowners don't say no. They just go quiet. QuoteCloser writes your quotes, follows up for you, and gets you more 5-star reviews, so more of your estimates turn into booked jobs.",
    calc: "unsold-quotes",
    calcIntro: "Enter your numbers and see what unsold quotes cost you each year.",
    pains: [
      "You drive out, measure, write a quote… and never hear back.",
      "Following up feels pushy, and you're on a job site all day anyway.",
      "Writing proper quotes at night eats into family time.",
      "The shop down the road has twice your Google reviews.",
    ],
    tools: [
      ["Quote Builder", "Talk or type the job details. Get a professional quote with Good, Better and Best options."],
      ["Quote Follow-up", "A friendly 5-touch text and email sequence for every open quote, written in your voice."],
      ["Review Booster", "Review requests to send after each job, plus replies to every Google review."],
      ["Seasonal Marketing", "Google Business posts and promos for tune-up season, storm season and slow months."],
    ],
    price: 59,
    businesses: ["HVAC", "Plumbing", "Electrical", "Roofing", "Painting", "Landscaping", "Handyman", "Other trade"],
    faq: [
      ["Do I have to change my scheduling or invoicing software?", "No. QuoteCloser works alongside whatever you use now (Jobber, Housecall Pro, paper). It focuses on one thing: turning quotes into jobs."],
      ["I'm not a computer person. Is this for me?", "Yes. If you can send a text, you can use it. You answer a few questions about the job and it writes the rest."],
      ["Will my customers know it's AI?", "The messages are written in plain, friendly language and sent by you. You review everything before it goes out."],
    ],
  },
  {
    slug: "cleanquote",
    brand: "CleanQuote",
    industry: "Cleaning",
    audience: "residential & commercial cleaning companies",
    title: "CleanQuote | Price cleaning jobs in seconds and keep recurring clients",
    description: "Free cleaning price calculator with Good/Better/Best options, plus AI tools to follow up on quotes, keep recurring clients and get more reviews.",
    eyebrow: "For cleaning companies",
    headline: "Quote faster. ",
    highlight: "Keep clients longer.",
    sub: "Price any home in seconds with three options, follow up on every quote automatically, and turn one-time cleans into recurring clients.",
    calc: "cleaning-price",
    calcIntro: "Price a home with Good, Better and Best options. Adjust the rate to your market.",
    pains: [
      "Every quote request means a callback, a walkthrough and guesswork on price.",
      "One-time customers rarely become recurring ones.",
      "Recurring clients cancel quietly and you find out too late.",
      "You know reviews matter but never have time to ask.",
    ],
    tools: [
      ["Instant Quote Builder", "Size, rooms and condition in, and a polished three-option quote out, ready to text."],
      ["Quote Follow-up", "Gentle follow-ups for every quote that hasn't booked yet."],
      ["Recurring Converter", "After a one-time clean, a message sequence that offers a recurring plan."],
      ["Review Booster", "Review requests after every clean, plus replies to your Google reviews."],
    ],
    price: 39,
    businesses: ["Residential cleaning", "Commercial cleaning", "Move-in / move-out", "Airbnb turnovers", "Other"],
    faq: [
      ["Is the calculator accurate for my area?", "It's a starting point. Set your own hourly rate and it uses a simple, transparent time estimate you can sanity-check against your own jobs."],
      ["Do I need special software?", "No. Everything works from your phone and saves to Google Sheets."],
      ["Does it replace my booking system?", "No. It works alongside it and focuses on winning and keeping clients."],
    ],
  },
  {
    slug: "clientflow",
    brand: "ClientFlow",
    industry: "Freelancers",
    audience: "freelance designers, writers, developers, VAs & consultants",
    title: "ClientFlow | Win more projects and get paid on time",
    description: "Free freelance rate calculator, plus AI tools that write proposals, follow up with quiet leads, handle scope creep and chase late invoices.",
    eyebrow: "For freelancers",
    headline: "Win the project. ",
    highlight: "Get paid on time.",
    sub: "Proposals with three packages in a minute, follow-ups for leads that go quiet, polite answers to scope creep, and invoice reminders that actually get paid.",
    calc: "freelance-rate",
    calcIntro: "Find the minimum rate that hits your income goal, and your package prices.",
    pains: [
      "Writing a custom proposal takes an evening, and half the time you hear nothing.",
      "\"Just one more small change\" keeps turning into free work.",
      "Chasing late invoices is awkward, so you put it off.",
      "You're not sure your rates actually cover taxes and time off.",
    ],
    tools: [
      ["Proposal Writer", "Paste the client's brief and get a proposal with Starter, Standard and Premium packages."],
      ["Lead Follow-up", "Follow-ups for proposals that go quiet, friendly and never needy."],
      ["Scope-Creep Replies", "Polite \"happy to, here's what that costs\" responses for extra requests."],
      ["Invoice Chaser", "Reminders at 7, 14 and 30 days overdue that stay professional."],
    ],
    price: 19,
    businesses: ["Design", "Writing / content", "Development", "Marketing", "Virtual assistant", "Consulting", "Photo / video", "Other"],
    faq: [
      ["Can't I just use ChatGPT?", "You could, but you'd be writing prompts from scratch every time. ClientFlow is set up for freelance sales: your packages, your voice, and a tracker of every lead and invoice in Google Sheets."],
      ["Does it send emails for me?", "It writes them; you send them. You stay in control of every client conversation."],
      ["Is the rate calculator free?", "Yes, it's free and needs no sign-up."],
    ],
  },
  {
    slug: "raisedesk",
    brand: "Raise Desk",
    industry: "Startups",
    audience: "pre-seed & seed founders",
    title: "Raise Desk | Run your fundraise like a sales pipeline",
    description: "Free fundraise calculator for dilution, runway and investor pipeline, plus AI tools for investor outreach, follow-ups and monthly updates.",
    eyebrow: "For pre-seed & seed founders",
    headline: "Run your fundraise like a ",
    highlight: "sales pipeline.",
    sub: "Know exactly how many investors you need to reach, write outreach that gets meetings, follow up without being annoying, and send investor updates in minutes.",
    calc: "raise-math",
    calcIntro: "See your dilution, runway and how many investors you need to contact.",
    pains: [
      "Your investor list lives in a messy spreadsheet and your head.",
      "\"Keep me posted\" investors fall through the cracks.",
      "Writing a personal note to 150 investors takes weeks.",
      "Monthly updates slip, and so does investor trust.",
    ],
    tools: [
      ["Investor Pipeline", "Paste names and notes and get a prioritized tracker with stage and next step."],
      ["Outreach Writer", "Personalized cold emails and warm-intro requests your connectors can forward."],
      ["Follow-ups", "Timely nudges for investors who went quiet or asked you to keep them posted."],
      ["Investor Updates", "Paste your metrics and wins and get a clean monthly update."],
    ],
    price: 49,
    businesses: ["Pre-seed", "Seed", "Series A", "Not raising yet"],
    faq: [
      ["Is this a CRM?", "It's lighter than a CRM: your pipeline lives in a Google Sheet you own, and AI does the writing and the reminders."],
      ["Is my data shared with investors?", "No. Nothing is sent anywhere unless you send it."],
      ["Is the calculator financial advice?", "No. It's simplified math for planning; talk to your lawyer about terms."],
    ],
  },
  {
    slug: "rebook",
    brand: "Rebook",
    industry: "Salons & spas",
    audience: "salons, barbers, nail studios, med spas & massage therapists",
    title: "Rebook | Fill empty chairs and win back lapsed clients",
    description: "Free no-show and lapsed-client calculator, plus AI messages that cut no-shows, win back regulars and get more reviews.",
    eyebrow: "For salons, barbers & spas",
    headline: "Fill empty chairs. ",
    highlight: "Win back regulars.",
    sub: "Reminder and rebooking texts that cut no-shows, \"we miss you\" messages that bring lapsed clients back, and a steady stream of 5-star reviews.",
    calc: "no-show",
    calcIntro: "See what no-shows and lapsed clients cost you each year.",
    pains: [
      "A no-show is an hour you can't sell again.",
      "Regulars drift away and you only notice months later.",
      "You mean to post promos and ask for reviews, but the day fills up.",
      "Slow Tuesdays stay slow.",
    ],
    tools: [
      ["No-show Saver", "Friendly reminder and confirmation texts that cut no-shows."],
      ["Win-back Messages", "Personal \"we miss you\" texts for clients who haven't booked in a while."],
      ["Promo Planner", "A month of promos and posts for holidays, slow days and new services."],
      ["Review Booster", "Review requests after every visit, plus replies to your Google reviews."],
    ],
    price: 39,
    businesses: ["Hair salon", "Barbershop", "Nails", "Med spa", "Massage / wellness", "Lashes / brows", "Other"],
    faq: [
      ["Does it work with my booking app?", "Yes. It writes the messages; you send them from the booking app or phone you already use."],
      ["Will messages sound robotic?", "No. They're written in your salon's voice, and you can edit anything before it goes out."],
      ["Is the calculator free?", "Yes, free with no sign-up."],
    ],
  },
  {
    slug: "coachdesk",
    brand: "CoachDesk",
    industry: "Coaches & trainers",
    audience: "personal trainers, online coaches & fitness studios",
    title: "CoachDesk | Keep clients longer and fill your programs",
    description: "Free client retention calculator, plus AI tools for check-ins, program launches, lead follow-up and renewals.",
    eyebrow: "For personal trainers & coaches",
    headline: "Keep clients longer. ",
    highlight: "Fill every program.",
    sub: "Check-in messages that keep clients motivated, launch content for your next program, and follow-ups that turn inquiries into paying clients.",
    calc: "client-retention",
    calcIntro: "See how much each client is worth when fewer of them quit.",
    pains: [
      "Clients go quiet after week three and cancel a month later.",
      "Inquiries from Instagram DMs never get a proper follow-up.",
      "Every program launch means a week of writing posts and emails.",
      "Renewals feel like a hard sell.",
    ],
    tools: [
      ["Client Check-ins", "Personal weekly check-in messages based on each client's goals."],
      ["Launch Kit", "Posts, stories and emails to fill your next program or challenge."],
      ["Lead Follow-up", "Replies and follow-ups for every inquiry and free-trial lead."],
      ["Renewal Messages", "Progress recaps that make renewing an easy yes."],
    ],
    price: 29,
    businesses: ["Personal trainer", "Online coach", "Fitness studio", "Nutrition coach", "Yoga / Pilates", "Other"],
    faq: [
      ["Does it write workouts?", "No. You're the expert. CoachDesk handles the messaging and marketing around your coaching."],
      ["Will it sound like me?", "Yes. Tell it your style once and every message follows it. Edit anything before it goes out."],
      ["Is the calculator free?", "Yes, free with no sign-up."],
    ],
  },
  {
    slug: "landlordkit",
    brand: "LandlordKit",
    industry: "Landlords",
    audience: "small landlords with 1–20 units",
    title: "LandlordKit | Run your rentals in minutes a week",
    description: "Free rental cash flow calculator, plus AI tools for listings, maintenance replies, tenant notices and Schedule E expense sorting.",
    eyebrow: "For small landlords",
    headline: "Run your rentals in ",
    highlight: "minutes a week.",
    sub: "Listings that fill vacancies, clear replies to maintenance requests, professional notices and renewals, and expenses sorted for tax time.",
    calc: "rental-cashflow",
    calcIntro: "Check a rental's monthly cash flow, cap rate and cash-on-cash return.",
    pains: [
      "Vacancy listings take forever to write and still get the wrong applicants.",
      "Maintenance texts arrive at 10pm and you're not sure how to reply.",
      "Renewal and rent-change letters need to sound professional.",
      "Tax time means a shoebox of receipts.",
    ],
    tools: [
      ["Listing Writer", "Clear, accurate rental listings that highlight what renters care about."],
      ["Tenant Replies", "Calm, professional replies to maintenance requests and questions."],
      ["Notices & Renewals", "Draft renewal offers and notices to review against your local rules."],
      ["Expense Sorter", "Paste your transactions and get them sorted into Schedule E categories."],
    ],
    price: 19,
    businesses: ["1 unit", "2–4 units", "5–20 units", "20+ units"],
    faq: [
      ["Does it screen tenants?", "No. Screening decisions stay with you. LandlordKit helps with writing, organizing and bookkeeping."],
      ["Are the notices legally valid?", "They're drafts. Rules vary by state and city, so check them against local law or with a lawyer before sending."],
      ["Is the calculator free?", "Yes, free with no sign-up."],
    ],
  },
  {
    slug: "listingdesk",
    brand: "ListingDesk",
    industry: "Real estate",
    audience: "real estate agents & small teams",
    title: "ListingDesk | Follow up with every lead and past client",
    description: "Free real estate income goal calculator, plus AI tools for listings, open-house follow-ups, past-client nurture and social posts.",
    eyebrow: "For real estate agents",
    headline: "Every lead followed up. ",
    highlight: "Every past client remembered.",
    sub: "Listing descriptions in seconds, open-house follow-ups the same day, and a steady rhythm of touches that keeps past clients sending referrals.",
    calc: "agent-goal",
    calcIntro: "Work backwards from your income goal to the leads you need each week.",
    pains: [
      "Open-house sign-ins sit in a pile until they've gone cold.",
      "Past clients forget your name by their next move.",
      "Listing descriptions and social posts eat your evenings.",
      "You know follow-up wins deals, but there are only so many hours.",
    ],
    tools: [
      ["Listing Writer", "Property details in, compelling and accurate listing copy out."],
      ["Open-House Follow-up", "Same-day follow-ups for every sign-in, tailored to what they said."],
      ["Past-Client Nurture", "A year of personal touches: home anniversaries, market updates, check-ins."],
      ["Social Posts", "Just-listed, just-sold and local-market posts for the week."],
    ],
    price: 49,
    businesses: ["Solo agent", "Small team", "Broker / owner", "New agent"],
    faq: [
      ["Does it replace my CRM?", "No. It writes the messages and keeps a simple follow-up list in Google Sheets; use it alongside your CRM."],
      ["Is listing copy fair-housing safe?", "It's instructed to describe the property, not the people, but always review listings before publishing."],
      ["Is the calculator free?", "Yes, free with no sign-up."],
    ],
  },
];
